export const TUTORIALSPOINT_TOPICS: string[] = [
  // Programming Languages
  "python",
  "java",
  "javascript",
  "typescript",
  "cprogramming",
  "cpp",
  "csharp",
  "ruby",
  "php",
  "go",
  "rust",
  "swift",
  "kotlin",
  "scala",
  "perl",
  "r",
  "matlab",
  "lua",
  "haskell",
  "groovy",
  "dart",
  "julia",
  "fortran",
  "cobol",
  "vba",
  "powershell",

  // Web / Backend
  "reactjs",
  "angularjs",
  "vuejs",
  "nodejs",
  "expressjs",
  "django",
  "flask",
  "fastapi",
  "spring",
  "spring_boot",
  "hibernate",
  "rubyonrails",
  "laravel",
  "symfony",
  "asp.net",
  "blazor",
  "svelte",
  "nuxtjs",

  // Frontend
  "html",
  "css",
  "html5",
  "css3",
  "bootstrap",
  "sass",
  "less",
  "jquery",
  "webpack",
  "graphql",
  "redux",
  "rxjs",
  "d3js",
  "threejs",

  // Databases
  "sql",
  "mysql",
  "postgresql",
  "mongodb",
  "redis",
  "sqlite",
  "cassandra",
  "neo4j",
  "couchdb",
  "dynamodb",
  "oracle",
  "mariadb",
  "elasticsearch",
  "influxdb",

  // DevOps / Cloud
  "docker",
  "kubernetes",
  "jenkins",
  "git",
  "github",
  "terraform",
  "ansible",
  "vagrant",
  "nginx",
  "apache",
  "aws",
  "azure",
  "gcp",
  "devops",
  "prometheus",
  "grafana",
  "helm",
  "linux",
  "unix",
  "bash",
  "centos",
  "ubuntu",

  // Data Science / AI
  "machine_learning",
  "deep_learning",
  "artificial_intelligence",
  "tensorflow",
  "pytorch",
  "keras",
  "numpy",
  "pandas",
  "matplotlib",
  "scipy",
  "scikit_learn",
  "nlp",
  "opencv",
  "data_science",
  "statistics",

  // Big Data
  "hadoop",
  "spark",
  "kafka",
  "hive",
  "pig",
  "hbase",
  "flink",
  "airflow",

  // Mobile
  "android",
  "ios",
  "flutter",
  "react_native",
  "xamarin",

  // Security
  "ethical_hacking",
  "cyber_security",
  "cryptography",
  "network_security",
  "penetration_testing",

  // CS Fundamentals
  "design_pattern",
  "data_structures_algorithms",
  "compiler_design",
  "operating_system",
  "computer_network",
  "dbms",

  // Tools
  "excel",
  "tableau",
  "power_bi",
  "jira",
  "maven",
  "gradle",
  "junit",
  "selenium",
  "jest",
  "microservice_architecture",
  "json",
  "xml",
  "yaml",
  "regex",
  "vim",
  "intellij_idea",
  "visual_studio_code",
  "tomcat",
];

const MAX_SUGGESTIONS = 8;

export function getSuggestions(input: string): string[] {
  if (!input) return [];
  const q = input.toLowerCase();
  const prefix = TUTORIALSPOINT_TOPICS.filter((t) => t.startsWith(q));
  const substr = TUTORIALSPOINT_TOPICS.filter((t) => !t.startsWith(q) && t.includes(q));
  return [...prefix, ...substr].slice(0, MAX_SUGGESTIONS);
}
